[package]
name = "activity-logs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }
dirs = "6.0.0"
owo-colors = "4.2.1"
rustyline = "16.0.0"
